name: Website Offline Monitor # 站点离线时推送消息

on:
  workflow_dispatch:  # 手动触发
  schedule:  # 定时触发
    - cron: '*/5 * * * *'  # 每5分钟执行一次

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lynx
        run: |
          sudo apt-get update
          sudo apt-get install -y lynx

      - name: Fetch Website Status
        id: fetch_status
        run: |
          # 获取状态码
          response=$(curl -k -Ls -o /dev/null -w "%{http_code}" "${{ secrets.URL }}" || echo "0")
          status_code="$response"
          
          # 如果无法建立连接，返回错误信息
          if [[ "$status_code" == "0" ]]; then
            echo "::set-output name=status_code::0"
            echo "::set-output name=summary::无法建立连接，网站可能不可用。"
            exit 1
          fi

          # 获取网页内容并提取有效文本
          content=$(lynx -dump "${{ secrets.URL }}")
          
          # 清理内容并提取前200个字符
          summary=$(echo "$content" | sed 's/^\s*//;s/\s*$//' | awk 'NR>1' | tr '\n' ' ' | sed 's/[^[:print:]]//g' | cut -c 1-200)
          echo "::set-output name=status_code::$status_code"
          echo "::set-output name=summary::$summary"

      - name: Send to DingTalk
        run: |
          status_code="${{ steps.fetch_status.outputs.status_code }}"
          summary="${{ steps.fetch_status.outputs.summary }}"
          webhook_url="https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.ACCESS_TOKEN }}"
          title="网页监控"

          # 根据状态码生成摘要信息
          if [[ "$status_code" == "200" || "$status_code" == "301" || "$status_code" == "302" ]]; then
            echo "网站正常访问，无需推送消息。"
          else
            case "$status_code" in
              400) summary="错误：返回状态码 400; 请求无效; 内容摘要：$summary" ;;
              401) summary="错误：返回状态码 401; 未授权; 内容摘要：$summary" ;;
              403) summary="错误：返回状态码 403; 禁止访问; 内容摘要：$summary" ;;
              404) summary="错误：返回状态码 404; 页面未找到; 内容摘要：$summary" ;;
              500) summary="错误：返回状态码 500; 服务器内部错误; 内容摘要：$summary" ;;
              502) summary="错误：返回状态码 502; 网关错误; 内容摘要：$summary" ;;
              503) summary="错误：返回状态码 503; 服务不可用; 内容摘要：$summary" ;;
              504) summary="错误：返回状态码 504; 网关超时; 内容摘要：$summary" ;;
              *)   summary="错误：返回状态码 $status_code; 内容摘要：$summary" ;;
            esac
            
            curl -X POST "$webhook_url" \
              -H 'Content-Type: application/json' \
              -d "{\"msgtype\": \"markdown\", \"markdown\": {\"title\": \"$title\", \"text\": \"$summary\"}}"
          fi
